# Exported from Render on 2024-03-22T13:21:40Z
services:
- type: web
  name: pixd
  runtime: node
  repo: https://github.com/susudeepa/pixd
  branch: main
  plan: free
  envVars:
  - fromGroup: PIXD credentials
  region: singapore
  buildCommand: npm install
  startCommand: node index.js
  domains:
  - www.pixd.live
  - pixd.live
  autoDeploy: false
version: "1"